title: "John Wang" # your name (or website title) here
logo: "/images/GettyImages-1228988128-1-784x523.jpeg?raw=true"
description: >
  Hi! I'm an undergraduate student at the University of California, Berkeley studying Economics, CS, and Stat. 
  <br><br>
  In my free time, I enjoy playing chess, doing outdoorsy stuff like hiking and kayaking, and trying new restaurants. I love taking photos, and scroll down if you want to check out some of the best food I've ever eaten.
  <br><br>
  Website still under construction
  <br><br>
  <a href='https://www.linkedin.com/in/john-j-wang/'><img src='images/linkedin.png' alt='LinkedIn' style='width:30px;height:30px;border:0;margin-right:5px;'></a>
  <a href='https://github.com/john-j-wang'><img src='images/github.png' alt='GitHub' style='width:30px;height:30px;border:0;margin-left:5px;'></a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
