title: John Wang # your name (or website title) here
logo: "/images/GettyImages-1228988128-1-784x523.jpeg?raw=true" # your photo (or logo) here
description:
  undergrad uc berkeley 
  <br><br>
  450 lp grandmaster adc
  <br><br>
  <a href="https://www.linkedin.com/in/john-j-wang/">LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
