title: "John Wang" 
logo: "/images/GettyImages-1228988128-1-784x523.jpeg?raw=true"
description: >
  Hi! I'm an undergrad at the University of California, Berkeley studying Economics, CS, and Stat. My passion is for random events and probability, and  
  I am particularly interested in using statistical and computational models to better understand and gain deeper insight into financial markets. 

  <br><br>
  
  In my free time, I enjoy learning chess, doing outdoorsy stuff like hiking and kayaking, as well as trying new restaurants.
  One of my hobbies is taking photos of food &mdash; <a href='/food'>click here</a> if you want to check out some of the best food I've ever eaten.
  
  <hr>
  <a href='/files/JohnWang_DS_2024%20(2).pdf' target='_blank'>Resume</a> 
  <br>
  <a href='/contact-me'>Contact</a> 
  <br>
  
  <a href='https://www.linkedin.com/in/john-j-wang/'><img src='/images/linkedin.png' alt='LinkedIn' style='width:30px;height:30px;border:0;margin-right:5px;'></a>
  <a href='https://github.com/john-j-wang'><img src='/images/github.png' alt='GitHub' style='width:30px;height:30px;border:0;margin-left:5px;margin-right:5px'></a>
  <a href='https://www.chess.com/member/ilr13s'><img src='/images/chess.png' alt='Chess.com' style='width:30px;height:30px;border:0;margin-left:5px;'></a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
